services:
  db:
    image: postgres:15
    container_name: smart-diet-db
    restart: always
    environment:
      POSTGRES_USER: rose_user
      POSTGRES_PASSWORD: mypassword123
      POSTGRES_DB: smart_diet_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # ✅ RabbitMQ 설정
  rabbitmq:
    image: rabbitmq:3-management
    container_name: smart-diet-rabbitmq
    restart: always
    ports:
      - "5672:5672" # RabbitMQ 기본 포트
      - "15672:15672" # RabbitMQ 관리 콘솔 포트
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
